version: '3'
services:
  fsa-app:
    container_name: fsa-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '861:8000'
    volumes:
      - .:/app

  fsa-db:
    container_name: fsa-db
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: eSlS3cr3t
      POSTGRES_DB: fastgraph
    ports:
      - "863:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    # volumes:
      # - ./db:/docker-entrypoint-initdb.d
      # - db_data:/var/lib/mysql

  fsa-pgadmin:
    image: dpage/pgadmin4
    container_name: fsa-pgadmin
    restart: unless-stopped
    ports:
      - "862:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    depends_on:
      - fsa-db
